import 'chat_message.dart';

/// The complete response returned by the ThaiLLM API after a chat completion.
class ChatResponse {
  /// Unique identifier for this completion.
  final String id;

  /// Unix timestamp of when this completion was created.
  final DateTime created;

  /// The model identifier echoed from the API.
  final String model;

  /// One or more completion choices returned by the model.
  final List<ChatChoice> choices;

  /// Token usage statistics for this request.
  final ChatUsage usage;

  const ChatResponse({
    required this.id,
    required this.created,
    required this.model,
    required this.choices,
    required this.usage,
  });

  /// Convenience getter for the content of the first choice.
  ///
  /// Returns an empty string when no choices are available.
  String get content => choices.isNotEmpty ? choices.first.message.content : '';

  /// Convenience getter for the finish reason of the first choice.
  String? get finishReason =>
      choices.isNotEmpty ? choices.first.finishReason : null;

  factory ChatResponse.fromJson(Map<String, dynamic> json) {
    final choicesList = (json['choices'] as List<dynamic>? ?? [])
        .map((c) => ChatChoice.fromJson(c as Map<String, dynamic>))
        .toList();

    return ChatResponse(
      id: json['id'] as String? ?? '',
      created: DateTime.fromMillisecondsSinceEpoch(
        ((json['created'] as num?)?.toInt() ?? 0) * 1000,
      ),
      model: json['model'] as String? ?? '',
      choices: choicesList,
      usage: ChatUsage.fromJson(
        json['usage'] as Map<String, dynamic>? ?? {},
      ),
    );
  }

  @override
  String toString() =>
      'ChatResponse(id: $id, model: $model, content: $content)';
}

/// A single completion choice returned by the model.
class ChatChoice {
  /// Zero-based index of this choice.
  final int index;

  /// The message generated by the model.
  final ChatMessage message;

  /// Why the model stopped generating tokens.
  final String? finishReason;

  const ChatChoice({
    required this.index,
    required this.message,
    this.finishReason,
  });

  factory ChatChoice.fromJson(Map<String, dynamic> json) {
    final msgJson = json['message'] as Map<String, dynamic>? ?? {};
    final roleStr = msgJson['role'] as String? ?? 'assistant';
    final role = ChatRole.values.firstWhere(
      (r) => r.value == roleStr,
      orElse: () => ChatRole.assistant,
    );

    return ChatChoice(
      index: (json['index'] as num?)?.toInt() ?? 0,
      message: ChatMessage(
        role: role,
        content: msgJson['content'] as String? ?? '',
      ),
      finishReason: json['finish_reason'] as String?,
    );
  }
}

/// Token usage statistics for a single API request.
class ChatUsage {
  /// Tokens consumed by the prompt / input messages.
  final int promptTokens;

  /// Tokens generated in the completion.
  final int completionTokens;

  /// Total tokens used (prompt + completion).
  final int totalTokens;

  const ChatUsage({
    required this.promptTokens,
    required this.completionTokens,
    required this.totalTokens,
  });

  factory ChatUsage.fromJson(Map<String, dynamic> json) => ChatUsage(
        promptTokens: (json['prompt_tokens'] as num?)?.toInt() ?? 0,
        completionTokens: (json['completion_tokens'] as num?)?.toInt() ?? 0,
        totalTokens: (json['total_tokens'] as num?)?.toInt() ?? 0,
      );

  @override
  String toString() =>
      'ChatUsage(prompt: $promptTokens, completion: $completionTokens, total: $totalTokens)';
}
